export const GALLERY = [
  {
    id: 0,
    name: "A dog that buys his own beer.",
    image: "assets/images/IMG_7111.jpg",
    width: 16,
    height: 9,
    featured: true,
  },
  {
    id: 1,
    name: "A Doberman Pinscher watching over students at MSUM.",
    image: "assets/images/MSU9073.jpg",
    width: 2,
    height: 3,
    featured: true,
  },
  {
    id: 2,
    name: "A doodle that walks himself.",
    image: "assets/images/GUS-IMG_7144.jpg",
    width: 2,
    height: 3,
    featured: true,
  },
  {
    id: 3,
    name: "A doodle fetching a cold one.",
    image: "assets/images/04-Gus-BB-Comercial.jpg",
    width: 16,
    height: 9,
    featured: true,
  },
  {
    id: 4,
    name: "A dog in a store heeling off-lead.",
    image: "assets/images/02-Gus-BB-Comercial.jpg",
    width: 16,
    height: 9,
    featured: true,
  },
  {
    id: 5,
    name: "A Doberman Pinscher sitting on a pickle ball court.",
    image: "assets/images/KONA-IMG_7640.jpg",
    width: 2,
    height: 3,
    featured: true,
  },
  {
    id: 6,
    name: "A Golden Retriever in the conformation ring.",
    image: "assets/images/conformation-retriever.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 7,
    name: "A doodle holding a bone in front of Scheels.",
    image: "assets/images/gus-bone-2.jpg",
    width: 2,
    height: 3,
    featured: false,
  },
  {
    id: 8,
    name: "A Husky waiting for a treat.",
    image: "assets/images/husky-vert.jpg",
    width: 2,
    height: 3,
    featured: false,
  },
  {
    id: 9,
    name: "A Basset Hound doing scent work.",
    image: "assets/images/scent-work-1.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 10,
    name: "A Lab puppy focusing on it's handler.",
    image: "assets/images/puppy-lab.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 11,
    name: "A Doberman Pinscher sitting by the fire.",
    image: "assets/images/kona-firepit.jpg",
    width: 2,
    height: 3,
    featured: false,
  },
  {
    id: 12,
    name: "A dog doing agility.",
    image: "assets/images/agility.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 13,
    name: "A Border Collie running.",
    image: "assets/images/border-collie-competition.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 14,
    name: "A Schitzu mix waiting for a treat.",
    image: "assets/images/Chewy-IMG_6820.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 15,
    name: "A group of Bearded Collies showing in conformation.",
    image: "assets/images/conformation-1.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 16,
    name: "A doodle retrieving over the high jump.",
    image: "assets/images/FPO-071021_NOC_68634-2.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 17,
    name: "A Doberman Pinscher chilling on the deck.",
    image: "assets/images/IMG_7270.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 18,
    name: "A group of working dogs learning obedience.",
    image: "assets/images/line-of-dogs.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 19,
    name: "A Border Terrier doing scent work.",
    image: "assets/images/scent-work-2.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
  {
    id: 20,
    name: "A Rottweiler doing scent work.",
    image: "assets/images/scent-work-3.jpg",
    width: 3,
    height: 2,
    featured: false,
  },
];
