export const GALLERY = [
  {
    id: 0,
    name: "A dog that buys his own beer.",
    image: "assets/images/IMG_7111.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 1,
    name: "A Doberman Pinscher watching over students at MSUM.",
    image: "assets/images/_MSU9073.jpg",
    width: 3,
    height: 4,
  },
  {
    id: 2,
    name: "A doodle that walks himself.",
    image: "assets/images/GUS-IMG_7144.jpg",
    width: 3,
    height: 4,
  },
  {
    id: 3,
    name: "A doodle fetching a cold one.",
    image: "assets/images/04-Gus-BB-Comercial.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 4,
    name: "A dog in a store heeling off-lead.",
    image: "assets/images/02-Gus-BB-Comercial.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 5,
    name: "A Doberman Pinscher sitting on a pickle ball court.",
    image: "assets/images/KONA-IMG_7640.jpg",
    width: 3,
    height: 4,
  },
  {
    id: 6,
    name: "A Golden Retriever in the conformation ring.",
    image: "assets/images/conformation-retriever.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 7,
    name: "A doodle holding a bone in front of Scheels.",
    image: "assets/images/gus-bone-2.jpg",
    width: 3,
    height: 4,
  },
  {
    id: 8,
    name: "A Husky waiting for a treat.",
    image: "assets/images/husky-vert.jpg",
    width: 3,
    height: 4,
  },
  {
    id: 9,
    name: "A Basset Hound doing scent work.",
    image: "assets/images/scent-work-1.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 10,
    name: "A Lab puppy focusing on it's handler.",
    image: "assets/images/puppy-lab.jpg",
    width: 4,
    height: 3,
  },
  {
    id: 11,
    name: "A Doberman Pinscher sitting by the fire.",
    image: "assets/images/kona-firepit.jpg",
    width: 3,
    height: 4,
  },
];
